### ISSUE TITLE
L10n: Configure weblate or scripts to output JSON translation files with 2 space indention

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#113]
Reproduction:
* Export the JSON translation file from weblate

Actual result:
* The JSON file has 4 space indention.
* The entire file shows in git as changed.

Expected result:
* The JSON file has 2 space indention.
* Only the strings actually changed show in git as changed.

Workaround:
* `sed -e "s|^    |  |" -i l10n/locales/*/messages.json`

**Comment by benbucksch** [comment]
Unfortunately, this seems to create conflicts between the git repo and weblate, so that weblate cannot merge the changes strings into git.

**Comment by jermy-c** [comment]
Please try:

1. Delete project, make sure all translation sources are cleared
2. Click the wrench icon in the menu to go to `/manage`
3. Select the `Add-ons` settings or tab
4. Find and install `Customize JSON output` add-on
5. Set ` JSON indentation` to `2` and ` JSON indentation style ` to spaces
6. Add the project back again

Addon
https://docs.weblate.org/en/latest/admin/addons.html#customize-json-output

Reason

- Weblate imports the JSON files with 4 space indents and doesn't change it afterwards

**Comment by benbucksch** [comment]
> Click the wrench icon in the menu to go to /manage

I have no access to `/manage` on the hosted.weblate.org instance.

**Comment by jermy-c** [comment]
When I download the JSON file manually there’s only 2 space indents. So I guess the problem only happens in a PR.

**Comment by jermy-c** [comment]
Not 100% sure it'll work or you have access to it. But maybe try:

1. Go to the project
2. Click on the `Manage` tab/dropdown
3. Select `Add-on`
4. Find and install `Customize JSON output` add-on
5. Set ` JSON indentation` to `2` and ` JSON indentation style ` to spaces
6. Wait for edits to the translation because only the translation edited will take effect

**Comment by benbucksch** [comment]
Yes, that worked. Thank you!
