### ISSUE TITLE
Translation: Missing UI strings

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#115]
Elena will fill in the details

**Comment by benbucksch** [comment]
![image](https://github.com/mustang-im/mustang/assets/1907525/2b54a788-e77a-4aa0-af4f-0d7cb407a007)

* "Search" header
* "Search for"

**Comment by raffikastudio** [comment]
![Screenshot (410)](https://github.com/mustang-im/mustang/assets/96830139/7eefab44-17b2-4774-9b75-b5f838fd30d0)
* "Recommended apps"
* "All the cathegory pane"
* "Description of each app"

**Comment by raffikastudio** [comment]
![Screenshot (411)](https://github.com/mustang-im/mustang/assets/96830139/301c3802-fc06-49be-8967-fe19712ed725)

* "Home"
* "Personal address book" and "Collected contacts" (tool tips) hovering the icons top left and in each contact header bottom right (close to actions) 

![Screenshot (412)](https://github.com/mustang-im/mustang/assets/96830139/f8fa3404-d41c-40f9-82cf-0d3f70b80c1d)

**Comment by benbucksch** [comment]
> "Personal address book" and "Collected contacts" 

These are the default account names, created in app/logic/

**Comment by benbucksch** [comment]
>     * "Recommended apps"
>     * All the cathegory pane
>     * Description of each app

This is the "App store". The content comes from a JSON file. We will translate this later.

**Comment by benbucksch** [comment]
Teams and WhatsApp are brand names. They stay in English.

**Comment by raffikastudio** [comment]
![WhatsApp Image 2024-07-01 at 18 59 42_939a15f2](https://github.com/mustang-im/mustang/assets/96830139/0db848aa-33f8-472f-b41e-2deb05e0822c)


* "Call"

**Comment by raffikastudio** [comment]
![Screenshot (421)](https://github.com/mustang-im/mustang/assets/96830139/3cde6491-044c-4894-ab8a-c51265eeb5b4)

The hover (tooltip) in "Mark as spam" is in english in both arabic and italian

**Comment by raffikastudio** [comment]
![Screenshot (423)](https://github.com/mustang-im/mustang/assets/96830139/143b9c95-4205-4de8-8b32-881ef13248f0)

* "76 mails"
* "INBOX"
* The time

**Comment by jermy-c** [comment]
>  "76 mails"
> "Call"

Was not translated by AI. Some languages could not be completely be translated by AI.

> "INBOX"

Not sure about this one. I don't see it in the code.

**Comment by benbucksch** [comment]
>     * "76 mails"

TODO

>     * "INBOX"

Fixed
Note that the other folder names are coming from the server and are user-set.

>     * The time

I fixed that already on master

**Comment by raffikastudio** [comment]
![image](https://github.com/user-attachments/assets/5811f906-3032-44f4-8252-543d841a8d87)

**Comment by benbucksch** [comment]
This is the island. This is new and therefore not yet part of the translations.
