### ISSUE TITLE
EWS: Error "terminated"

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#124]
After a while of Mustang just sitting there doing nothing, I see an error "terminated".

The stack trace is:
![image](https://github.com/mustang-im/mustang/assets/1907525/2bb6f24a-03dd-4e09-8feb-ca8626b92e44)

**Comment by benbucksch** [comment]
@NeilRashbrook #118 has higher priority than this

**Comment by NeilRashbrook** [comment]
This seems to happen when your HTTPS socket closes unexpectedly. Since this is happening on the backend, there should be another stack trace on the console, not that it would help (the stack trace here references a line number `206` which has never been inside the `callStream` function).

**Comment by benbucksch** [comment]
I've had Mustang with an EWS account running over night, and I don't see the error anymore.
