### ISSUE TITLE
SQL: UNIQUE Constraint failed

### ISSUE THREAD

**Issue by papiermache** [mustang-im/mustang#126]
I just created a 2nd account in Parula. First one was imap, this second is ews; got this error (“UNIQUE contstraint failed…”) 
![Picture1](https://github.com/mustang-im/mustang/assets/5385881/7b1fb5bd-7544-4c4a-a2f0-a6bb1db7d63c)

**Comment by benbucksch** [comment]
@papiermache Thanks for the bug report. We seems to receive the same folder name twice.

Could you please also tell us:
* The stack track ("Bug" button on top right of error notification)
* What actions you did before the problem appeared?

**Comment by benbucksch** [comment]
@papiermache ping

**Comment by papiermache** [comment]
Hi Ben, sorry but i got frustrated enough with Parula and put it aside (back to T-bird). The UI seems to have a mindset that I don't follow. I just tried to attach an image, its not showing for me so not sure its present.
![Screenshot 2024-07-16 155016](https://github.com/user-attachments/assets/91ae6055-25b5-4bea-bce7-8a40dad65cb6)

**Comment by benbucksch** [comment]
> The UI seems to have a mindset that I don't follow

What trouble did you have? We'd like to make it easy for you.

**Comment by benbucksch** [comment]
> Why is Accounts greyed out?

Accounts is a header label for what follows.
"Microsoft rick@" and "Microsoft VqaOntario" are your 2 email accounts that you configured.

> is Settings going to be a gear (most typical) or train signals?

Good point about the 2 different settings icons. We'll look at that.

**Comment by benbucksch** [comment]
I don't see this anymore, since we have the locking
