### ISSUE TITLE
After I renaming a folder, the folder name in the screen title does not update 

### ISSUE THREAD

**Issue by raffikastudio** [mustang-im/mustang#164]
Reproduction steps:
Change Name folder
Click "Rename"

Expected result:
As soon as I click rename, the right name appears immediately everywhere where there was the old name.
    
    
Actual result:
The name doesn't change in the block header and not even in the top header, it changes only on the folder pane on that specific folder._

**Comment by benbucksch** [comment]
FIXED by fe2fea604
