### ISSUE TITLE
OWA: Login is stuck with OWA web frontend in login window

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#179]
Reproduction:
1. Add neil@beonex.onm account, using OWA protocol, from the account setup dialog
2. Login
3. Get msgs
4. Restart Mustang
5. Click on Inbox, to login

Actual result:
* Step 2: First login worked
* Step 5: Login window shows OWA web frontend and does not automatically close
* When you close the window, error: "Auth window was closed by user"

![image](https://github.com/user-attachments/assets/6af97b1a-ade2-4942-abb9-6aeee6ce6ace)

Expected result:
* We reliably recognize that we're logged in
* Fetch mail in Mustang

**Comment by NeilRashbrook** [comment]
Note that I needed to choose "No" to the "Stay Logged In" prompt to reproduce this.

Mustang is offering the wrong OWA configuration; the host needs to be `outlook.office.com` for OWA; EWS and ActiveSync are correct in offering `outlook.office365.com`.

Annoyingly you can't easily correct it using manual setup because that doesn't start with the selected values.

(When I first launched Mustang after removing `~/.mustang` I got a database locked error, but I wasn't able to reproduce that either.)

**Comment by benbucksch** [comment]
> I needed to choose "No" to the "Stay Logged In" prompt to reproduce this.

You are entirely correct that I chose this option: Don't stay loggedin in, and don't remember that choice. I should have mentioned that in the reproduction. I'm sorry that I didn't.

> OWA configuration; the host needs to be outlook.office.com for OWA; EWS and ActiveSync are correct in offering outlook.office365.com.

I've corrected the config on our ISPDB that Mustang uses:
https://v1.ispdb.net/office365.com

Interesting enough, we use office365.com for OWA in Thunderbird ISPDB, which is used for Owl:
https://autoconfig.thunderbird.net/v1.1/office365.com
but then we go in the Owl code and fix it up:
```
  if (owaURL.hostname == "outlook.office365.com") {
    // https://outlook.office365.com/ often 301 redirects to outlook.office.com
    // which means that's the hostname where the X-OWA-COOKIE actually gets set.
    // Generically detecting the redirect complicates the code, so instead we
    // just anticipate the redirect here.
    owaURL.hostname = "outlook.office.com";
```

...and the code comment there explains this bug here.

offtopic:

> manual setup ... doesn't start with the selected values

IIRC, it does after a failed verify login, but not in this this case. Thanks for reporting that. Noted.
