### ISSUE TITLE
Yahoo set up failed

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#181]
**Reproduction steps:**
I set up my yahoo account 
I choose the workspace (personal)

**Actual result:**
-the yahoo account appears in the list of accounts
-an error message appears: 'no such column: tagName'

![image](https://github.com/user-attachments/assets/b48da1b4-e35a-4835-ab8d-ea24ebd36c62)

![image](https://github.com/user-attachments/assets/3c97c78e-7269-413a-9c41-97c77d8e54a1)

![image](https://github.com/user-attachments/assets/3052fcd3-4edb-4d92-9431-f7ef270ed517)

![image](https://github.com/user-attachments/assets/a4ba85d5-4624-4cb8-90e8-5503965e3314)

![image](https://github.com/user-attachments/assets/2d050a7f-3997-4d27-a4ec-ec3fc7b42264)

![image](https://github.com/user-attachments/assets/c11650a9-c102-4c66-a78a-a8af9de6a1b8)

![image](https://github.com/user-attachments/assets/360a4cff-8bbc-4543-922b-7c689d66c906)

![image](https://github.com/user-attachments/assets/a292cc82-25b3-40b3-bc44-2eb905f8f351)

![image](https://github.com/user-attachments/assets/c07a140d-1f25-4bd5-8ff8-bfbc124f39d5)

![image](https://github.com/user-attachments/assets/16123841-ec67-4084-a27e-0f7e2b85b853)

**Comment by benbucksch** [comment]
This is due to a database schema change. Can you please delete your AppData/Mustang folder? Sorry about that.
