### ISSUE TITLE
Composer: Send allows multiple clicks - Sending 4 emails instead of one

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#186]
**Reproduction steps:**
Open email composer
Insert an email address
Enter
Insert the txt, subject
Click Send (nothing happens)
After 10 seconds I click again 

**Expected result:**
Sending one email

**Actual result:**
It's sending 4

![grafik](https://github.com/user-attachments/assets/47276c08-d8a7-497e-a2b3-f6585271921c)

![grafik](https://github.com/user-attachments/assets/78df48e5-0da4-437c-a686-fd1c89f98cfd)

![grafik](https://github.com/user-attachments/assets/659dcde9-81af-46fd-b6e2-d75f1baff9d5)

![grafik](https://github.com/user-attachments/assets/bcfd8e9d-faef-4385-b07f-abbb1919aa74)

![grafik](https://github.com/user-attachments/assets/94292f19-cbca-46ea-9221-3f57f3d2cf15)

**Comment by benbucksch** [comment]
This should have been fixed 7 months ago in git commit dd456638.
@Unwrap-at Elena, could you please re-test whether this bug still exists?
