### ISSUE TITLE
IMAP: MIME source not yet downloaded

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#188]
Reproduction:
* Occasionally, when clicking on a message

Actual result:
* The message body pane shows the error message: "MIME source not yet downloaded"

Expected result:
* The message body pane shows the message body

Cause:
* `EMail` object is in an inconsistent state:
* `.needToLoadBody` is true
* `.downloadCompleted` is true
* `.readBody()` does not result in `.html` nor `.text` property being filled, therefore `needToLoadBody` stays true
* `IMAPEMail.download()` fetches the message correctly.
* `IMAPEMail.fromFlow()` returns early and does not populate `.mime`, because `downloadCompleted` is true.
* Consequently, `.parseMIME()` finds `.mime` empty and fails with error "MIME source not yet downloaded".

The problem is that inconsistent state. I don't know why `.downloadCompleted` is true, but `readBody()` cannot read the body. I suspect is a problem during writing to the SQL database. There must be some edge case where we fail to write the body or the MIME source or both, but nonetheless write `downloadCompleted = true` to the DB.

**Comment by jermy-c** [comment]
> I suspect is a problem during writing to the SQL database. There must be some edge case where we fail to write the body or the MIME source or both, but nonetheless write downloadCompleted = true to the DB.

I checked the database and indeed it is because we're failing to write the body to the database. The `plaintext` and `html` columns are empty for many of the messages even though `downloadComplete` is true.

**Comment by benbucksch** [comment]
> I checked the database and indeed it is because we're failing to write the
> body to the database. The plaintext and html columns are empty for many of the
> messages even though downloadComplete is true.



Can you find out why that happens, please?

**Comment by jermy-c** [comment]
Ok, will do. I did see many calls of `SQLSave()` when changing Email Accounts/Folders with `plaintext` and `html` being passed with null so it might be from the caller.

**Comment by benbucksch** [comment]
That's normal. We first download the headers (without body), and save them to DB. downloadComplete should be false then. Then, we download the content. Once we have the full MIME source, parsed it and the body, then downloadComplete should be true.

readMessage() does not read the entire message from DB, even if it's in the DB. That's to make the load from DB go faster. Because the content might be large.

I have a suspicion:
It could be that we then do a save() of that half-loaded message. And that save is overwriting the complete msg in the DB with the half-loaded one.

**Comment by benbucksch** [comment]
It appears there are at least 2 code paths that do that: `IMAPFolder.updateNewFlags()` and `IMAPFolder.messageFlagsChanged()`. Both call `await this.saveMsgs(updatedMessages)` (not new msgs). `SQLEMail.save()` then overwrites the existing message. That's the bug.

That's because `SQLEMail.readAll()` reads the headers, but not the body. So, `downloadComplete` will be read as `true`, but the body will still be empty - in memory. Doing `SQLEMail.save()` will the save a broken and inconsistent state back into the DB.

**Comment by benbucksch** [comment]
How to manually fix the broken DB:
`UPDATE email SET downloadComplete = false WHERE plaintext IS NULL;`

**Comment by benbucksch** [comment]
@jermy-c I've landed a potential fix. But I don't know whether it will fix it. Could you please test it? You first need to fix your DB (see my last comment above), then run with master.

**Comment by jermy-c** [comment]
Yes, the fix works. I also checked database with `SELECT * FROM email WHERE plaintext = NULL AND html = NULL AND downloadComplete = 1;` and I don't see any with empty plaintext or html and has downloadComplete.

**Comment by benbucksch** [comment]
I have not seen this error message anymore. Seems like it worked.
