### ISSUE TITLE
IMAP: After delete messages: Messages from the last days disappear

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#189]
Reproduction:
* Delete a message from INBOX

Actual result:
* The message disappears from the INBOX and appears in Trash (correct)
* After a few seconds (maybe 10 seconds), all new messages from the last few days disappear from the inbox.
* No error in UI nor on console

Expected result:
* The message disappears from the INBOX and appears in Trash
* No other messages disappear

**Comment by josiaspb** [comment]
![Screenshot from 2024-09-10 16-41-19](https://github.com/user-attachments/assets/6452d114-8993-4482-b698-a35c247a191c)
I place some console log commands to trace what is going on when you delete a message.
I notice the deleteLocally function along runs many times after you delete a message.
Not clear to me why

**Comment by josiaspb** [comment]
![Screenshot from 2024-09-10 16-45-14](https://github.com/user-attachments/assets/705bbb77-5e8d-4c9e-b870-b8ec1dc4af1f)
After deleteMessage finished deleteMessageLocally runs again not clear who calls the fucntion.

**Comment by josiaspb** [comment]
The function checkDeletedMessages calls deleteMessageLocally but even when you coment the line the messages dissapears so it seems this is not the cause.

**Comment by benbucksch** [comment]
This was fixed by the locks.

**Comment by benbucksch** [comment]
This was fixed by the locks in git commit 74267993
