### ISSUE TITLE
Msg viewer: Links don't open the system browser

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#191]
**Reproduction steps:**
Click on a message 
Click on a link

**Expected result:**
The browser should show me the website.

**Actual result:**
When I click on the link, the link becomes red and nothing happens.

**Comment by benbucksch** [comment]
* This depends on your "default browser" settings in your OS. What do you have selected there?
* Also, is that browser already open/running when you click on the link?
* Does the browser open a tab with the page of the link?

**Comment by Unwrap-at** [comment]
mm
1. not sure
2. yes it is
3. no, that's the problem, nothing happens when you click

interesting fact though, this problem doesn't exist in the tread view.
In thread view when I click a links it opens on the browser in a different window.

**Comment by benbucksch** [comment]
The "thread view" (left-most icon, in the view switcher at the top left of the email content) is not in an iframe, whereas the normal msg view is in a `<WebView>`.

**Comment by benbucksch** [comment]
On Linux, links in the `<WebView>` open for me (sometimes, depending on system situation).

**Comment by benbucksch** [comment]
See e2/src/main/index.ts line 40 setWindowOpenHandler()

**Comment by josiaspb** [comment]
setWindowOpenHandler() do not see webview events. When a user clicks a link inside the webview, the main process do not notice the event and do not open the link.

When a user clicks a webview link, I propose to two options: 
-Send a message from the render process to the main process with the URL to open by shell.openExternal(). 
-Open the link from the webview.

**Comment by benbucksch** [comment]
> 
> setWindowOpenHandler() do not see webview events. When a user clicks a link inside the webview, the main process do not notice the event and do not open the link.

This was originally the same for the app UI. As you can see from the comment in the code, we had to add target==_blank.


> 
> 
> When a user clicks a webview link, I propose to two options:
> -Send a message from the render process to the main process with the URL to open by shell.openExternal().
> -Open the link from the webview.

Go ahead and make a patch (or multiple alternatives).
-- 
Sent from my phone. Please excuse the brevity.

**Comment by benbucksch** [comment]
@josiaspb Could you please post progress and findings about this bug here in the github issue?

* In app/frontend/Shared/WebView.svelte, function `haveWebView()`, add an event listener for `will-navigate`. In the event listener, do an `alert("changing page");` or `console.log("changing page");` (the latter would appear in the console of the frontend, not the webview)
* In app/logic/util/convertHTML.ts, remove line `node.setAttribute("target", "_blank");` -- for testing purposes only! Do not commit this.

Then, see whether the event listener fires.

Then, see whether Electron `<webview>` has another event hat tells you that the page tries to open a window. If so, add that event listener, and put back the `target "_blank"` and see whether that open window event fires.

**Comment by josiaspb** [comment]
I tested your suggestion. When you remove the traget="_blank" attribute from the anchor elements inside the webview the "will-navigate" event is fired after you click a link.
![Screenshot from 2024-09-18 15-41-56](https://github.com/user-attachments/assets/419fed80-e646-4410-ac80-6a0265d63660)

**Comment by josiaspb** [comment]
The event is fired on the webview because the webview tries to navigate to a another site. On the otherhand I was not able to set up listener for events fired on the elements inside the webview, example clinking a link.

**Comment by benbucksch** [comment]
Yes, because it's a different document.

**Comment by benbucksch** [comment]
I've tried
```
    webviewE.addEventListener('new-window', async (event) => {
      const url = event.url;
      console.log("new window for", url);
      event.preventDefault()
      await appGlobal.remoteApp.shell.openExternal(url);
    });
```
but it doesn't fire when I click on a link in an email.
