### ISSUE TITLE
Error: UID FETCH Command Arguments Invalid 

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#194]
Reproduction:

    Open Mustang
    Click an email account
    Click Inbox
    Click on a message

Actual result:

    After a few seconds Error message appears: UID FETCH Command Arguments Invalid
    
    
![image](https://github.com/user-attachments/assets/f2245f95-8099-4729-aa46-a2a218efb145)

![image](https://github.com/user-attachments/assets/493abbad-41a4-40bb-aaf0-61e3702e66f0)

![image](https://github.com/user-attachments/assets/0d6048aa-295e-4d6f-b0c5-8e8f5c7eb067)

**Comment by josiaspb** [comment]
Hi @Unwrap-at Helena
Is this error still reproducible for you?
I try on my side my with different accounts but did not catch this behavior.

**Comment by josiaspb** [comment]
Could you please let me know the specific email provider you where using when the error happenend?
For what I see on the screenshot the email provider was not Yahoo nor Gmail.

**Comment by benbucksch** [comment]
Probably fixed with the locking.

@Unwrap-at If you see this error again, please reopen.
