### ISSUE TITLE
Search: UI freezes after loading an email folder then clicking search

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#195]
**Reproduction**

1. Open Mustang
2. Click on an email account
3. Click on a folder
4. Click search

**Expected Result**

1. Shows search field

**Actual Result**

1. UI freezes
2. No search field shows up

<img width="951" alt="圖片" src="https://github.com/user-attachments/assets/f7b4479f-6a6a-44e2-973b-96fc20abb956">

**Error**
```
SearchPane.svelte:222 Uncaught (in promise) TypeError: searchFieldEl.focus is not a function
    at SearchPane.svelte:222:21
    at run (chunk-TFC4DMOW.js?v=6b2de17c:28:10)
    at Array.map (<anonymous>)
    at chunk-TFC4DMOW.js?v=6b2de17c:1844:52
    at flush (chunk-TFC4DMOW.js?v=6b2de17c:1131:9)
```

**Comment by benbucksch** [comment]
Thanks for finding this. Do you want to fix it? Fix should be simple, given the debug info you posted.

**Comment by jermy-c** [comment]
You're welcome. Yes, I'll fix it.
