### ISSUE TITLE
AOL: OAuth window shows "something went wrong"

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#211]
### Reproduction
* Set up an @aol.com account in Mustang

### Actual result
* AOL auth page shows: "Whoops. An error occurred."
* Nothing relevant in the Error Console of the auth window (Ctrl-Shift-I within the auth window)

![image](https://github.com/user-attachments/assets/0d11c035-4ab6-475e-924d-252ac07acd6f)

### Expected result:
* AOL auth page shows a password login prompt

**Comment by jermy-c** [comment]
It seems to be the redirect URI  is invalid
```
error: invalid_request
error_description: invalid redirect uri
```

**Comment by benbucksch** [comment]
In the App registration, the done URL was https://mustang.im/loggedin , whereas it was https://www.mustang.im/loggedin in our app. I fixed the app registration. It may take a while for the server farm to update.

**Comment by benbucksch** [comment]
That fixed the bug above.

Now I cannot log in because of the Google Captcha, and AOL saying "too many failed attempts" (there were no failed attempts at all). But that's another issue...
