### ISSUE TITLE
IMAP: Cannot read properties of undefined (reading 'messageId')

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#214]
**Reproduction**

1. Open an IMAP Email folder
2. Select threaded view
3. Scroll through and click on emails

**Actual Result**

1. Emails seem normal
2. There's an error banner at the top
3. After a while, it shows the error in the email body area
4. After that, it shows `Could not parse command` in the email body area when click on another email

**Expected Result**

1. No error banner

**Possible Cause**

- There might be some missing emails in the thread and it's trying to read those
- Some of the email ids are wrong because I see some unrelated emails in the thread

**Screenshots**

Screenshot 1
<img width="1436" alt="圖片" src="https://github.com/user-attachments/assets/4035a9da-123f-45df-8102-6b3ef99ded9a">

Screenshot 2
<img width="646" alt="圖片" src="https://github.com/user-attachments/assets/878ff283-0442-40ea-b604-5cad8b25d155">

```
error.ts:14 TypeError: Cannot read properties of undefined (reading 'messageId')
    at IMAPEMail.fromFlow (IMAPEMail.ts:56:43)
    at IMAPEMail.download (IMAPEMail.ts:41:10)
    at async IMAPEMail.loadBody (EMail.ts:332:9)
```
```
IMAPCommandError: Could not parse command
    at IMAPFolder.runCommand (IMAPFolder.ts:86:15)
    at async IMAPEMail.download (IMAPEMail.ts:31:19)
    at async IMAPEMail.loadBody (EMail.ts:332:9)
```
```json
{
    "id": 424510,
    "success": false,
    "message": "Command failed",
    "backendStack": "Error: Command failed\n    at ImapFlow.reader (file:///Users/jeremyc/Documents/GitHub/mustang/e2/out/main/index.js:112309:24)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
    "originalCall": {
        "id": 424510,
        "path": "func",
        "arg": {
            "obj": "34892393680216903680",
            "name": "fetchOne",
            "args": [
                "null",
                {
                    "plainObject": {
                        "uid": true,
                        "size": true,
                        "threadId": true,
                        "envelope": true,
                        "source": true,
                        "flags": true
                    }
                },
                {
                    "plainObject": {
                        "uid": true
                    }
                }
            ]
        }
    },
    "response": {
        "tag": "3A3",
        "command": "BAD",
        "attributes": [
            {
                "type": "TEXT",
                "value": "Could not parse command"
            }
        ]
    },
    "responseStatus": "BAD",
    "responseText": "Could not parse command"
}
```

**Comment by benbucksch** [comment]
Most instances of this bug were fixed with the IMAP locking in git commit 74267993.

There is one remaining case: If the message is deleted by another client, and Mustang has not refreshed the message list, and then the user clicks on it to read it, then this error may appear.
