### ISSUE TITLE
Mail viewer: undefined reading split 

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#217]
### Steps
* click my IMAP account in the folder pane
* click inbox
* click on a message

### Actual result
Message list appears but when I click to a message, the content never appears

![image](https://github.com/user-attachments/assets/0f496517-3ce4-4dc3-8f17-601508c0b268)

### Expected result
Seeing the email content after clicking to a message in the message pane.

**Comment by benbucksch** [comment]
I saw the same error message occasionally.

**Comment by benbucksch** [comment]
I don't see this anymore. Please reopen, if you see it again.
