### ISSUE TITLE
ActiveSync: Saving sync key after processing error?

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#225]
See https://github.com/mustang-im/mustang/pull/221#discussion_r1787059872

Concerning:
* `ActiveSyncAccount` global sync key
* `ActiveSyncAddressbook.makeSyncRequest()`

We saving the sync state before we had a chance to parse and save the result. If this fails for some reason, we missed these changes or (worse) become incoherent with our local copy.

Instead, we need to:
1. Lock (I guess that's what `queuedSyncRequest()` does)
2. Fetch
3. Parse the result
4. Set and save the sync key.
5. Unlock

Please give it some thought which error situations can happen and how we should recover from them.

* If the processing of the changes throws reproducibly on a given change set, then if we don't save the sync key in case of error, the next attempt would run into the same error again and be stuck forever.
* If the error is temporarily, e.g. because the received data is corrupted on the wire, then we would want to re-try.

I'm not sure what is correct and more reliable here.

For the code, one way would be to wrap the async parsing function, so you could still keep saving the sync key in the same function here. Compare `IMAPFolder.runCommand()` and its callers.

**Comment by NeilRashbrook** [comment]
I've created branch `neil/activesync-save-sync-key-later` but I don't seem to be able to test it right now because I'm getting a lot of timeout errors.

**Comment by benbucksch** [comment]
@NeilRashbrook This is fixed, right?

**Comment by NeilRashbrook** [comment]
This was fixed by #233 and #263.

**Comment by benbucksch** [comment]
Great
