### ISSUE TITLE
Google set up failing

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#261]
Steps:
- I insert email and Password
- It says it found the server 
- I give permission in the Google window
- Then the Google window closes and it appears what you see in the picture 'Google Mail SMTP: Need OAuth2 login from IMAP'

![Screenshot (551)](https://github.com/user-attachments/assets/6a8f6916-31c2-4f5a-9c8a-5fa73fce8166)

**Comment by jermy-c** [comment]
The fix is here #240
