### ISSUE TITLE
Mac: Notarization fails

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#264]
When building 0.6.13, the notarization fails with failing to get some kind of JSON file from HTTP. Both Mac builds fail, and I've re-tried them multiple times. It still worked for 0.6.12, and there were no relevant changes to the build that could cause this problem. So, it must be a change on the side of Apple or Electron.

0.6.12 (Oct 16) success https://github.com/mustang-im/mustang/actions/runs/11367357692
0.6.13 (Nov 20) FAIL https://github.com/mustang-im/mustang/actions/runs/11927399831/job/33243445634
```
  • downloaded      url=https://github.com/electron/electron/releases/download/v32.2.5/electron-v32.2.5-darwin-x64.zip duration=2.426s
  • signing         file=dist/mac/Mustang.app platform=darwin type=distribution identity=DF954CB13... provisioningProfile=none
  ⨯ Unexpected token 'E', "Error: HTT"... is not valid JSON  failedTask=build stackTrace=SyntaxError: Unexpected token 'E', "Error: HTT"... is not valid JSON
SyntaxError: Unexpected token 'E', "Error: HTT"... is not valid JSON
    at JSON.parse (<anonymous>)
    at /Users/runner/work/mustang/mustang/e2/node_modules/@electron/notarize/src/notarytool.ts:79:25
```

**Comment by jermy-c** [comment]
The build is now successful:

https://github.com/mustang-im/mustang/actions/runs/11927399844/job/33277025812

We were blocked from notarizing the app because Apple wanted it us agree on their Apple Developer Program License Agreement. It appeared as the first item on the dashboard.

**Comment by benbucksch** [comment]
Same thing happened again. Are they going to keep **breaking** our builds?
