### ISSUE TITLE
Email doesn't show messages

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#275]
Steps:
I download the new version 0.6.14
I click mail app on the app bar
I click on the gmail account
I click on inbox

Actual:
Nothing happens, no list of messages, nothing

Expected:
I see the list of messages and so I select one and it opens on the right

![Screenshot (1053)](https://github.com/user-attachments/assets/912a26e2-9fd4-40bb-b42d-e770806fc247)
![Screenshot (1052)](https://github.com/user-attachments/assets/7da7584b-599b-4416-8b57-37a98694e02c)
![Screenshot (1051)](https://github.com/user-attachments/assets/ba4afca2-c75f-481c-88ad-6522f13ece8b)

**Comment by benbucksch** [comment]
Neil changed the database structure. Unfortuantely, you need to delete mail.db in Mustang settings and setup again.

**Comment by Unwrap-at** [comment]
ok thanks for telling me, I'll know next time
