### ISSUE TITLE
ActiveSync: Error Sync status 111 in "All messages"

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#281]
### Reproduction
1. Set up neil@ as ActiveSync account
2. Login, open Inbox and a few other folders
3. Click on "All accounts" | "All messages" in the folder pane

### Actual result
* Error: ActiveSync Sync status 111
* Stack:
![image](https://github.com/user-attachments/assets/3e7bf159-6289-45bd-b296-12f5772b1e6b)

### Expected result
* No error
* All messages display

**Comment by NeilRashbrook** [comment]
ActiveSync status 111 is equivalent to HTTP status 503 service unavailable, please retry later.

**Comment by benbucksch** [comment]
> ActiveSync status 111 is ... service unavailable, please retry later.

OK, so, that's missing throttling. Filed #327 .

**Comment by benbucksch** [comment]
git commit 874d67e1
