### ISSUE TITLE
Gmail: Unknown Mailbox: [Gmail]

### ISSUE THREAD

**Issue by jermy-c** [mustang-im/mustang#285]
**Reproduction**

1. Do a fresh login of a Gmail account
2. Click the small download icon on the [Gmail] account

**Actual Result**

1. Yellow banner at the top with `Unknown Mailbox: [Gmail] (now in authenticated state) (Failure)`

**Expected Result**

1. No error

**Stack**

```
error.ts:6 IMAPCommandError: Unknown Mailbox: [Gmail] (now in authenticated state) (Failure)
    at IMAPFolder.runCommand (IMAPFolder.ts:86:15)
    at async IMAPFolder.fetchUIDList (IMAPFolder.ts:262:5)
    at async IMAPFolder.checkDeletedMessages (IMAPFolder.ts:443:22)
    at async IMAPFolder.getNewMessages (IMAPFolder.ts:281:5)
    at async getMail (GetMailButton.svelte:55:16)
    at async catchErrors (error.ts:60:5)
```

_Mentioned in https://github.com/mustang-im/mustang/issues/284#issuecomment-2507504530_

**Comment by jermy-c** [comment]
The `[Gmail]` has a `\Noselect flag`.

https://github.com/emersion/go-imap/issues/181#issuecomment-379549587

**Comment by benbucksch** [comment]
Good point, thanks!

And I thought that only the old UW IMAP server had \NoSelect folders! 😀Go figure... 🙃

**Comment by benbucksch** [comment]
I don't think any user wants to see this folder in the UI. We need to special-case this, unfortunately. Thunderbird also does that.

@Jeremy @Elena: As a GMail user,  what do you expect to see in the folder hierarchy?

**Comment by jermy-c** [comment]
The folder hierarchy normally is just all the folders but not nested in [Gmail].

**Thunderbird**
<img width="186" alt="圖片" src="https://github.com/user-attachments/assets/50f47be5-3472-4441-8bbc-20ae292ce151">

**Gmail UI**
<img width="247" alt="圖片" src="https://github.com/user-attachments/assets/7fcaa8cc-399f-4703-9a32-ba4661a20e80">

**Comment by benbucksch** [comment]
You could add a special case `if .path == "[Gmail]"` to `IMAPAccount.readFolders()` or its caller.
