### ISSUE TITLE
Mail, both table view and vertical view, message list: the 'unread' dot doesn't work

### ISSUE THREAD

**Issue by Unwrap-at** [mustang-im/mustang#304]
Steps
Click the 'unread' dot next to the recipient name

Actual result
Nothing happens

Expected result
It should become bold and the dot should stay, even if the message is open on the message pane

If you click on the 'unread' dot in the message pane it works, the message appears to be 'unread' even in the message list.

![image](https://github.com/user-attachments/assets/620b2ae0-2e83-4a6c-ac44-cb69f0cf6e31)

**Comment by benbucksch** [comment]
Funny that you found this. You have the default setting to immediately mark as read, right? I think what happens is that it is marked as unread, then the message refreshes, and the message display refreshes, and then the message display immediately marks it as read again.

Not sure how to work around that.

**Comment by benbucksch** [comment]
Ah, I found the problem. One code line was running to late. Fixed.
