### ISSUE TITLE
Sentry: Upload source maps for releases

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#306]
I've already ran the Sentry wizard which should have configured vite to upload the source maps as part of the build, but there are still no source maps on Sentry for releases.

Sentry says:
"
Debug IDs

are a way of matching your source files to source maps. Follow all of the steps below to get a readable stack trace:

Installed SDK supports Debug IDs

Stack frame doesn't have Debug IDs
Uploaded Files Not Deployed

It seems you already uploaded artifacts with Debug IDs, however, this event doesn't contain any [Debug IDs ](https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/)yet. Generally this means that you didn't deploy the same files you injected the Debug IDs into. For Sentry to be able to show your original source code, it is required that you deploy the exact same files that you uploaded to Sentry.

If you are using a Sentry Plugin for your Bundler

, the plugin needs to be active when building your production app. You cannot do two separate builds, for example, one for uploading to Sentry with the plugin being active and one for deploying without the plugin. The plugin needs to be active for every build.

If you are utilizing Sentry CLI

, ensure that you deploy the exact files that the sentry-cli sourcemaps inject command has modified!

Read the Sentry Source Maps Documentation
to learn how to inject Debug IDs into your build artifacts and how to upload them to Sentry.
"

![image](https://github.com/user-attachments/assets/ab7622ce-fc95-418b-bdb9-8e7b221e4b47)

**Comment by jermy-c** [comment]
The source map was never generated we need to set `build.sourcemap = true` in `e2/electron.vite.config` for the renderer process but when I set it, I get this error.
```
transforming (2114) ../../../app/frontend/Mail/Tag/TagBubble.svelte3:09:40 PM [vite-plugin-svelte] /Users/jeremyc/Documents/GitHub/mustang/app/frontend/AppsBar/AppObject.svelte:2:0 A11y: <hbox> with click handler must have an ARIA role
1: <!-- svelte-ignore a11y-click-events-have-key-events -->
2: <hbox class="app-object" on:click={() => catchErrors(onOpen)}>
   ^
3:   <slot />
4: </hbox>
✓ 2786 modules transformed.
rendering chunks (1)...
<--- Last few GCs --->

[40281:0x150008000]    23339 ms: Scavenge (reduce) 2029.0 (2078.5) -> 2028.9 (2079.5) MB, 2.50 / 0.00 ms  (average mu = 0.447, current mu = 0.373) allocation failure; 
[40281:0x150008000]    24970 ms: Mark-Compact (reduce) 2032.7 (2082.2) -> 2032.4 (2083.2) MB, 1461.67 / 0.00 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1464 ms) (average mu = 0.250, current mu = 0

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----
```

Could it possible be the remote functions from jpc websocket?

I get the error even if I set it for main, preload and renderer processes. The main and preload processes don't have issues with generating a source map.

**Comment by benbucksch** [comment]
@jermy-c Tested with release 0.7.3, and I see the source in the stack traces now. Thank you!
