### ISSUE TITLE
Linux: App starter menu: Show in Internet/Mail category, not Utilities

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#313]
### Reproduction
* Install Mustang as .deb on Ubuntu desktop
* Open the main apps menu
* Find Mustang

### Actual result
* Mustang is in category "Utilities", like file manager and consoles

### Expected result
* Mustang is in category "Internet / "E-Mail", like Thunderbird and Evolution
* Note that there may be only a main catetory "Internet" or a subcategory "E-Mail", based on how many apps you have installed in that category.

### Code
* `e2/electron-builder.yml` setting `linux.category` is `Utility`.
* Find the correct category. Is it `Internet` or `Mail` or how exactly is it called?

**Comment by jermy-c** [comment]
There's a category called `Email` which fallback to `Office` or `Network` main categories.

https://specifications.freedesktop.org/menu-spec/latest/additional-category-registry.html

**Comment by benbucksch** [comment]
Thanks! That's the document I was looking for. Thanks for finding this.
