### ISSUE TITLE
Mac: Adapt sed script

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#96]
Please adapt the `sed` calls in app/build/parula-brand.sh so that they work on stock Mac, including the CI server.

Test locally. Once working locally, run "Parula Installers for Mac" job on CI, and ensure that it succeeds.

**Comment by jermy-c** [comment]
> MacOS `sed` doesn't support `-e`, but you could try switching to `Perl` - see branch `neil/sed-to-perl`, which I created because I thought that lack of the right `sed` was what the problem was on Windows.

Yeah, works perfectly. The exact code could be used for Mac OS, also. I tested it locally and I didn't install Perl so I guess it comes with Mac OS, also.

**Comment by benbucksch** [comment]
Merged to master.
