### ISSUE TITLE
Mac: Code signing

### ISSUE THREAD

**Issue by benbucksch** [mustang-im/mustang#97]
Actual result:
![image](https://github.com/mustang-im/mustang/assets/1907525/3462bcc4-9e03-4ce5-9f0b-85d1d92e92a6)
![image](https://github.com/mustang-im/mustang/assets/1907525/f670e366-5d1b-41c5-92bd-ef0e59e7b403)

Expected result:
* Installation happens smoothly with no warnings

Note: We're using "electron builder", so tutorials about "electron forge" (an alternative to "electron builder") may not be applicable.

Docs:
* https://www.electron.build/code-signing.html
* https://github.com/iffy/electron-updater-example
* https://www.electronjs.org/docs/latest/tutorial/code-signing
* https://stackoverflow.com/questions/48309773/code-signing-macos-app-with-electron

**Comment by benbucksch** [comment]
@jermy-c This is working now, right?

**Comment by jermy-c** [comment]
> @jermy-c This is working now, right?

Yes, it is working now but both Parula and Mustang use the same code signing certificate(Beonex one).

**Comment by benbucksch** [comment]
Yes, that's understood.

Thanks for making this work!

**Comment by jermy-c** [comment]
You're welcome!
